export const COLLECTIONS = {
  USERS: 'users',
  CURSOS: 'cursos',
  MODULOS: 'modulos',
  VAGAS: 'vagas',
  EMPRESAS: 'empresas',
  CANDIDATOS: 'candidatos',
  CANDIDATURAS: 'candidaturas',
  INSCRICOES: 'inscricoes',
  CERTIFICADOS: 'certificados',
  TESTES: 'testes',
  RESOURCES: 'resources',
  RESUMES: 'resumes',
  MATCHES: 'matches',
} as const;
